### ISSUE TITLE
Small issue with env config

### ISSUE THREAD

**Issue by shilov** [vectart/ember-cli-pace#1]
Found this only moments after you released it, and it's exactly what I was looking for :+1: 

Small issue I found with setting the config. If the theme is set but the color is not specified, errors are thrown:

```
Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:488:13)
  at Class.module.exports.included (/project/node_modules/ember-cli-pace/index.js:37:28)
```

**Comment by vectart** [comment]
@shilov Thanks a lot for the report—the npm package is updated to 0.0.7

**Comment by shilov** [comment]
That took care of it, kudos
