### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by jkneb** [vectart/ember-cli-pace#10]
Install fails at the bower install stage.

The command I did was: 
`ember install ember-cli-pace`

Gives me this error message: 
`Tag/branch master=vectart/pace#master# does not exist`

**Comment by jkneb** [comment]
`~ ember -v`

```
version: 1.13.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.2
npm: 2.13.3
os: darwin x64
```

**Comment by laantorchaweb** [comment]
Same as #12 the full error is this one:

```
version: 1.13.5
Installed packages for tooling via npm.
installing pace
Installing browser packages via Bower...
  not-cached git://github.com/vectart/pace.git#master=vectart/pace#master#
Tag/branch master=vectart/pace#master# does not exist
Error: Tag/branch master=vectart/pace#master# does not exist
```

**Comment by shripathee** [comment]
I am getting this issue as well with
ember-cli: 1.3.8
ember: 2.0.0

**Comment by aalasolutions-zz** [comment]
+1

```
ember install ember-cli-pace
version: 1.13.8
Installed packages for tooling via npm.
installing pace
DEPRECATION: passing vectart/pace#master directly to `addBowerPackageToProject` will soon be unsupported.
You may want to replace this with `addBowerPackageToProject('vectart/pace', 'master')`
Package vectart/pace=vectart/pace not found
Error: Package vectart/pace=vectart/pace not found
at createError (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
at /Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
at _fulfilled (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:863:30)
at Promise.promise.promiseDispatch (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:796:13)
at /Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:604:44
at runSingle (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
at flush (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:125:13)
at process._tickCallback (node.js:355:11)
```

**Comment by alvinvogelzang** [comment]
Experienced the same issue. I changed `this.addBowerPackageToProject('vectart/pace#master');` to `this.addBowerPackageToProject('vectart/pace', 'master');` in `blueprints/pace/index.js` and the install succeeds now. 

Problem is I receive another error when I run `ember serve`. It says `Pace theme CSS file was not found: blue/pace-theme-material.css`

I use 
ember-cli: 1.13.8
ember: 1.12.1

**Comment by aalasolutions-zz** [comment]
@alvinvogelzang Thanks for the idea, When I got the error I tried to download this package as development and then changed the file there. Then i was stuck how to test that in my build.

Here is what I have done
1. Install pace on ember 1.13.1 (i already had that as I was upgrading my code)
2. Install ember 1.13.8
3. Install pace in 1.13.8
4. Fix the line `addBowerPackageToProject('vectart/pace', 'master')` in node/pace/blueprint
5. Copy `bower_compnents/pace` folder from 1.13.1 to 1.13.8
6. Run `ember s`

or
1. Install pace on 1.13.8
2. Fix error off pace#master - 4th point from above
3. Add  `"pace": "vectart/pace#master",` in `bower.js`
4. run `bower install`
5. run `ember s`

It is working now, so I assume when we run install script it halts after downloading node packages and bower script dosnt get executed. as this line `addBowerPackageToProject('vectart/pace', 'master');` is having error so `bower install` will not install pace

I hope this will help users

**Comment by thiagodelgado111** [comment]
It fixed for me, thanks @aalasolutions

**Comment by laantorchaweb** [comment]
This issue is solved on the last release. Thanks everyone for reporting and provide solutions.
