### ISSUE TITLE
[ERROR]: Unable to install ember-cli-pace

### ISSUE THREAD

**Issue by abhilashlr** [vectart/ember-cli-pace#12]
Error thrown: Package vectart/pace=vectart/pace not found

**Comment by avaz** [comment]
+1

**Comment by SeyZ** [comment]
:+1:

**Comment by laantorchaweb** [comment]
same issue here, I've used this library on the past and it didn't have this problem.

**Comment by scottfister** [comment]
My PR fixes this https://github.com/vectart/ember-cli-pace/pull/14

**Comment by drewclauson** [comment]
@scottfister I couldn't get your PR to work with ember-cli 1.13.8, it gave me the same error Package vectart/pace=vectart/pace not found

**Comment by tiborpilz** [comment]
+1

**Comment by jaredcnance** [comment]
+1

**Comment by laantorchaweb** [comment]
This issue is solved on the last release.
