### ISSUE TITLE
Package vectart/pace=vectart/pace not found

### ISSUE THREAD

**Issue by drewclauson** [vectart/ember-cli-pace#17]
When install using ember-cli 1.13.8, I'm getting the error:
Package vectart/pace=vectart/pace not found

I tried install from #14 with the deprecated call fixed but that had the same issue.

**Comment by tiborpilz** [comment]
+1

**Comment by matthewnessworthy** [comment]
+1

**Comment by eelke** [comment]
+1

**Comment by kevinjalbert** [comment]
+1

**Comment by gregtap** [comment]
+1

**Comment by Kilowhisky** [comment]
+1

**Comment by planetexpress69** [comment]
+1

**Comment by antonbavykin1991** [comment]
+1

**Comment by cbetta** [comment]
+1 Any chance you could look into this @vectart ?

**Comment by hergaiety** [comment]
+1

**Comment by cbetta** [comment]
:(

**Comment by acerov** [comment]
+1 :(

**Comment by cdunn** [comment]
+1

**Comment by MarceloBorgesP** [comment]
+1

**Comment by Baskerville42** [comment]
+1
<img width="1195" alt="2016-02-01 20 58 14" src="https://cloud.githubusercontent.com/assets/5596941/12727665/935efa8c-c926-11e5-8c5f-b928cb31952e.png">

``` bash
$ ember -v
version: 1.13.13
node: 0.12.9
npm: 2.14.10
os: darwin x64
```

**Comment by laantorchaweb** [comment]
This issue is solved on the last release. Thanks everyone for reporting and provide solutions.
