### ISSUE TITLE
Installation of addon - `ember generate`command requires an entity name

### ISSUE THREAD

**Issue by OutOfNutella** [vectart/ember-cli-pace#2]
Hello !

I have some troubles in the installation of the addon.
I've already used PACE but in a non-ember-cli app.

In my new app made with ember-cli, I try to run `ember install ember-cli-pace`.
It installs bower and npm dependencies but it throws an error after that : 

> The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

I saw in ember-cli documentation that the command `ember generate` is used to create Blueprints.
So, I tried to run `ember generate pace` in order to generate it.
It seems It installed all dependencies correctly but I don't know if I'm doing something wrong.

After that, I run an 'ember build' but I've the following error

> Building...
> Arguments to path.join must be strings
> TypeError: Arguments to path.join must be strings
>     at Object.posix.join (path.js:471:13)
>     at Class.module.exports.included ([...]/frontend/node_modules/ember-cli-pace/index.js:73:32)
>     at EmberApp.<anonymous> 

An `ember serve` display to me a different error

> Pace theme CSS file was not found: blue/pace-theme-material.css
> Error: Pace theme CSS file was not found: blue/pace-theme-material.css
>     at Class.module.exports.included ([...]/frontend/node_modules/ember-cli-pace/index.js:82:15)
>     at EmberApp.<anonymous> 

Here is the result of `ember -v` : 

version: 0.2.3
node: 0.12.1
npm: 2.7.6

Also, bower version used is 1.4.1.

I'm a bit in trouble with all of that, so it would be helpful to get some precisions :)

Thank you !

**Comment by vectart** [comment]
@Pewel I've just created draft ember project, installed ember-cli-pace and gotten the same error, which is an ember-cli bug: https://github.com/ember-cli/ember-cli/issues/3831 Actually, the pace bower dependency was installed and `ember server` started successfully.

Regarding the lost CSS file, which operation system do you use?
Could you please try to execute `bower uninstall --save pace PACE && bower cache clean && ember g pace` and inform whether it fixed the problem?

**Comment by OutOfNutella** [comment]
First of all, thank you for your answer :)

Edit :  Your command fixed my problem about the lost CSS file ! Sorry, I didnd't see `pace` keyword after `ember g` :s 

Edit 2 : I solved the installation with the Fix explained in [#3831](https://github.com/ember-cli/ember-cli/issues/3831)
`ember server` started and Pace successfully loaded and available in my app console.

I have just one question : `ember server` make the build without error and `ember build` throws the error 

> Arguments to path.join must be strings

Is there something different between the build executed with `ember server` and the build with `ember build` ? 

Thank your for your explanations :)

**Comment by vectart** [comment]
@Pewel Thanks a lot for pointing at this issue!
I committed fix and the newest 0.0.12 version should work—please verify whether everything is okay or something might be improved.

**Comment by OutOfNutella** [comment]
Everything is good ! Serve and build commands work perfectly !

**Comment by vectart** [comment]
@Pewel sweet, thanks for the confirmation!
