### ISSUE TITLE
add collaborators

### ISSUE THREAD

**Issue by jamesdixon** [vectart/ember-cli-pace#23]
@vectart would you be willing to add collaborators so someone can merge these PRs and get things working again?

**Comment by laantorchaweb** [comment]
There's no movement on the account since september, I think it's time to make a fork and publish a new library onto NPM.

**Comment by jamesdixon** [comment]
@laantorchaweb would you be willing to collaborate to get it up to speed?

**Comment by jamesdixon** [comment]
I created a [new fork here](https://github.com/scoutforpets/ember-pace). It's now available on npm as `ember-pace`. I haven't done anything with it yet, but if there's anyone else who would want to help to get things working on 2.x and merge in some of the PRs, let me know and I'll add you as a collaborator.

**Comment by laantorchaweb** [comment]
@jamesdixon sure I'll do.

**Comment by jamesdixon** [comment]
@laantorchaweb thanks. just added you. i won't have any time in the next week or so to make any updates, but feel free to have a go at it.

**Comment by vectart** [comment]
@jamesdixon @laantorchaweb Sorry for the silence guys, you are collaborators now.

**Comment by laantorchaweb** [comment]
Thanks @vectart I've pushed some changes to fix the issues that we were having with installation, I tested it by installing directly from the github repo `ember install https://github.com/vectart/ember-cli-pace` and it's working as expected, could you push a new version to NPM? Thanks again!

**Comment by jamesdixon** [comment]
@vectart given that you may not have the time to continue maintenance on the repo, would it be better for us to stick with another branch so that one of us can publish to NPM?

**Comment by jamesdixon** [comment]
Or, looks like you can add multiple owners to `npm`: https://docs.npmjs.com/cli/owner

**Comment by vectart** [comment]
@jamesdixon I've added you as a collaborator, please feel free to publish new version
https://www.npmjs.com/package/ember-cli-pace

**Comment by jamesdixon** [comment]
thanks, @vectart!

@laantorchaweb i just tested locally using the latest version of ember (2.3.1) and everything appears to be working properly. would you like me to go ahead and publish? great work, btw

**Comment by laantorchaweb** [comment]
Great news! Sure let's move forward with this. Thanks.

**Comment by jamesdixon** [comment]
0.1.0 released. Looks like a bunch of the PRs/Issues can be closed. @laantorchaweb I noticed that you didn't merge your branch from my fork with the updated structure. Was it unneeded?

**Comment by laantorchaweb** [comment]
@jamesdixon thanks, I didn't merge that branch because I wanted to fix the installation with the minimum change to the code, we could upgrade the folder structure later now that we have something stable again. I think we can safely remove the fork now.

**Comment by jamesdixon** [comment]
@laantorchaweb :+1:
