### ISSUE TITLE
Not showing on route transition

### ISSUE THREAD

**Issue by temecom** [vectart/ember-cli-pace#26]
I have some long running promises in my routes model hook but the bar only shows on the last rendering step. How do I activate the pace bar on the route model() or willTransition() hook? 

Thanks 

Chris

**Comment by laantorchaweb** [comment]
If you're using `ajax` on your models it should be firing up, otherwise this is just a wrapper for the actual `pace.js` library so you can use all the options there on your `config/environment.js` file like:

```
restartOnPushState: true
```

Check the other options here:
http://github.hubspot.com/pace/
