### ISSUE TITLE
Does not find material theme

### ISSUE THREAD

**Issue by khornberg** [vectart/ember-cli-pace#28]
I installed fresh on an ember 2.4 app. When I set the theme to material, ember fails to build because the theme is not found. If I copy the material theme from `ember-cli-pace` to `bower_components/pace/<color>` then the theme is found and works well.

**Comment by vectart** [comment]
The material theme was merged into original pace package
HubSpot/pace#214

**Comment by khornberg** [comment]
Ok. So I think you are saying that it will be in the `pace` package at some point? I did a fresh install today and it was not there in the `bower` package.

**Comment by vectart** [comment]
@khornberg apparently, it's not released yet. Maybe it's worth to use `pace#master` meanwhile.

**Comment by joshsmith** [comment]
@khornberg you will definitely need to use `master` until they release another version. Would consider asking them for a `1.1` version bump that includes it.
