### ISSUE TITLE
Percent Title is not displaying properly on IE

### ISSUE THREAD

**Issue by ecehanece** [vectart/ember-cli-pace#32]
Hello,

I'm using pace loading bar on my web project. Great work by the way.
I have a problem with the percent title on IE. It's not displaying below the bar. When I looked up, it's on the top right side on the page. I think -ms-box-sizing attribute is the problem. Could you please fix this bug?

I appreciate your help. Have a good day.

**Comment by laantorchaweb** [comment]
Hey @ecehanece this is just a wrapper for the pace.js library, could you check if just using pace.js shows the same issue? in that case, maybe you can file that bug on their repo.

[https://github.com/HubSpot/pace/issues](https://github.com/HubSpot/pace/issues)

Thanks.

**Comment by joshsmith** [comment]
@ecehanece can you clarify if you're still having this issue?

**Comment by ecehanece** [comment]
Hey @JoshSmith it seems the issue is fixed. Thank you.

**Comment by joshsmith** [comment]
Thanks!
