### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by joshsmith** [vectart/ember-cli-pace#34]
Hi @vectart. I know open source is a lot of work that I don't take lightly. I can't thank you enough for putting all the hard work to get this project where it is today.

That said, I'm curious if you still intend to maintain the library. There are some open issues and pull requests that have been that way for awhile.

Is there any interest in handing off to another maintainer? I'd be happy to handle the transition myself, if you'd like.

Thanks!

**Comment by laantorchaweb** [comment]
Hey @JoshSmith I'm one of the maintainers of this project. Basically, I end up in this position after seeing installation problems on Ember 2.x and pushing some PRs, I remember at that time that vectart didn't have much time to work on the repo. I don't have the permissions to make you a maintainer but surely I can review and discuss any PR that you can provide. I'll look into the open issues this weekend.

**Comment by joshsmith** [comment]
@laantorchaweb @vectart given that much hasn't changed since I last checked in, any interest in handing this off now?

I'm really hesitant to make a competing fork, but this is a fairly important part of our project and I want to be sure I have confidence in the long-term here.

**Comment by vectart** [comment]
@JoshSmith sorry for the silence. You've been added as a collaborator, please feel free to maintain the library and let me know if I can help you more.

**Comment by joshsmith** [comment]
Thanks @vectart, and no problem. I think another nice thing is seeing if you could grant me access to `npm` as an owner? That way we can make sure changes from `master` do get released.

**Comment by vectart** [comment]
@JoshSmith sure, what's your NPM nickname?

**Comment by joshsmith** [comment]
@vectart great! It's `joshsmith`.

**Comment by vectart** [comment]
@JoshSmith done, thanks for your help!

**Comment by joshsmith** [comment]
Thanks @vectart!
