### ISSUE TITLE
Setting location.href to a mailto link causes indefinite progress bar

### ISSUE THREAD

**Issue by svmhdvn** [vectart/ember-cli-pace#36]
Not sure if this is an issue with this plugin or Pace itself, but when I try to do something like window.location.href="mailto:foo@bar.com", the loading indicator never stops. I tried adding mailto links to the ignoreURLs environment property, but that doesn't work (might be due to #16). Any way to get around this, preferrably using some configuration option in the pace ENV property?

**Comment by joshsmith** [comment]
@sivamahadevan I've not seen this myself; could you try a vanilla project that uses just Pace on its own and see if the same thing is replicable?

**Comment by svmhdvn** [comment]
@JoshSmith Just tried it and found that the problem wasn't Pace, it was a livereload websocket connection that was being tracked. It's resolved.

**Comment by joshsmith** [comment]
Thanks for the fast follow-up @sivamahadevan!
