### ISSUE TITLE
Pace loading is always displaying

### ISSUE THREAD

**Issue by manny-grewal** [vectart/ember-cli-pace#38]
I installed pace with 'ember install ember-cli-pace' then in my index.html I added these two lines:

`    <script data-pace-options='{"document":false, "eventLag":false, "elements": false, "restartOnRequestAfter":false }' src="js/pace.js"></script>`

`<link href="css/pace-style.css" rel="stylesheet" />`

I only want pace to work on ajax calls so I figure those pace-options will work fine. It shows the correct style however upon just loading localhost:4200 pace is always showing the loading bar. It never goes away at all. I have no idea what to do. I feel like setting those pace-options has done nothing.

**Comment by manny-grewal** [comment]
I solved this issue oddly just now, but I do not know why this is working. Basically by removing this

`<script data-pace-options='{"document":false, "eventLag":false, "elements": false, "restartOnRequestAfter":false }' src="js/pace.js"></script>`

It works fine. I have no idea why though and was hoping someone could shed some light.

**Comment by laantorchaweb** [comment]
Hi @manny-grewal the config options need to be on your `config/environment.js` file. Look at the docs for examples but basically is something like this:

```
ENV.pace = {
    theme: 'minimal',
    color: 'blue',
    catchupTime: 50,
    initialRate: .01,
    minTime: 100,
    ghostTime: 50,
    maxProgressPerFrame: 20,
    easeFactor: 1.25,
    startOnPageLoad: true,
    restartOnPushState: true,
    restartOnRequestAfter: 500,
    target: 'body',
    elements: {
      checkInterval: 100,
      selectors: ['body', '.ember-view']
    },
    eventLag: {
      minSamples: 10,
      sampleCount: 3,
      lagThreshold: 3
    },
    ajax: {
      trackMethods: ['GET', 'POST', 'DELETE', 'OPTIONS'],
      trackWebSockets: true,
      ignoreURLs: []
    }
  }
```
