### ISSUE TITLE
Config bug

### ISSUE THREAD

**Issue by williamhector** [vectart/ember-cli-pace#5]
Whenever I set any configurable options to false, such as restartOnPushState or restartOnRequestAfter, their default value is used instead.
I think it's line 48 of /index.js 
I'm not sure of the best approach, but I fixed it temporarily by changing line 48 to:
`_paceConfig[key] = baseConfig.pace.hasOwnProperty(key) ? baseConfig.pace[key] : _defaultPaceConfig[key];`

**Comment by andybluntish** [comment]
I submitted a PR to fix this, but have not heard anything from the author yet.

**Comment by vectart** [comment]
@williamhector @andybluntish Thanks a lot for the https://github.com/vectart/ember-cli-pace/pull/3 pull request, it's merged and 0.0.13 version is deployed to NPM. Please let me know, if something else might be improved!
