### ISSUE TITLE
[DOC] Configuration?

### ISSUE THREAD

**Issue by funtusov** [vectart/ember-cli-pace#6]
Thanks for the addon, but it seems that the documentation doesn't mention where to actually put the configuration overrides? Specifically, I'm trying to change the theme, could you please point me in the right direction?

**Comment by funtusov** [comment]
Ok, I found in an old edition of Readme: "To configure theme, append few lines to `config/environment.js`:" – I'd suggest adding that bit back :)

**Comment by vectart** [comment]
@funtusov Thank you for this point, I've updated Readme
