### ISSUE TITLE
What about other Pace themes?

### ISSUE THREAD

**Issue by GarPit** [vectart/ember-cli-pace#8]
Did you plan to add it?

**Comment by vectart** [comment]
@GarPit Basically, all [existing Pace themes](https://github.com/HubSpot/pace/tree/master/themes) are supported and might be configured like that:

``` js
var ENV = {
  pace: {
    theme: 'barber-shop',
    color: 'black'
};
```

Does it work for you?

**Comment by GarPit** [comment]
Nope. You don't have these themes among css files

**Comment by vectart** [comment]
@GarPit Add-on will try to find theme file in the Pace bower package
https://github.com/vectart/ember-cli-pace/blob/master/index.js#L71

**Comment by GarPit** [comment]
Oh, ok. This wasn't mentioned in README. Thanks!

**Comment by vectart** [comment]
@GarPit You are welcome, I'll improve the README
